name: Connect to Github runner with SSH

on:
  workflow_dispatch:

with:
  limit-access-to-actor: true           # Only the workflow initiator can connect

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup upterm session for debugging
        uses: owenthereal/action-upterm@v1